### ISSUE TITLE
Support Capistrano 3

### ISSUE THREAD

**Issue by mdespuits** [tomafro/recap#94]
Capistrano got a major release recently and it would be awesome if this would allow support for it. Any chance of that?

**Comment by tomafro** [comment]
Do you know what would need doing to support cap 3?  As I understand it
it's a pretty major change.

**Comment by mdespuits** [comment]
Yes, as I am looking at it now, it is a major change. Maybe a major version change for the gem?

**Comment by tomafro** [comment]
I think it would have to be a major version change.  I'm reticent to do it unless there's a very compelling benefit

**Comment by peregrinator** [comment]
It is a major change to capistrano but seems the right way forward in terms of DSL, etc. However it's back to the old shared and releases strategy... Definitely would love to see a version of recap that added that to Cap 3.x!

**Comment by mdespuits** [comment]
I'm hoping capistrano/capistrano#718 will pave the way for something like this.

**Comment by natebird** [comment]
This looks promising. Is there an update now that it was merged in?

**Comment by mdespuits** [comment]
Not yet. I have not had time to tackle it as the architecture to Capistrano 3 may change how Recap is structured. I definitely would like to get moving on that for my company, so it will eventually get done :worried:

**Comment by natebird** [comment]
Any update on this? Anything that can be done to help? Is this the thread to track?

**Comment by mdespuits** [comment]
@natebird I haven't made any progress. I've been incredibly busy of late and not focused on deployment. I haven't forgotten, but if someone else wants to pick up the helm, that would be amazing, too

**Comment by natebird** [comment]
I'll try to give it a shot in the next week or so. I'll push up a branch and post back here when I get a chance. Thanks for the quick response.

**Comment by MarkMurphy** [comment]
@natebird Have you made any progress on this?

**Comment by MarkMurphy** [comment]
Doesn't appear that @natebird has anything started but I'm willing to help get this done. I have some questions about some of the code in recap, if I can get someone to give me a hand with those then I'd be willing to get moving on this. 

Would be awesome if others would pitch in or help outline exactly what it is that needs to be done so that we have a clear list of tasks to complete.

**Comment by manuelmeurer** [comment]
I would be happy to chip in. Do you want to work in your own fork and accept PRs?

**Comment by MarkMurphy** [comment]
@manuelmeurer Yes. Thanks for volunteering.

**Comment by manuelmeurer** [comment]
Cool. How do we organize this then? Do you want me to look at something specific?

**Comment by MarkMurphy** [comment]
@manuelmeurer I guess that's what we need to figure out. I was thinking I would start buy updating Capistrano then start by rewriting all of the deploy tasks starting with deploy.rb and working my way backward.  I don't think we'll need /support/shell_command.rb anymore so I'll probably wipe that out.

We might have to create our own version of: https://github.com/capistrano/capistrano/blob/master/lib/capistrano/setup.rb

So that we can take advantage of the same way defaults and stage specific settings are loaded but skip the git tasks that would otherwise be loaded by: 

```
# line 16: https://github.com/capistrano/capistrano/blob/master/lib/capistrano/setup.rb
load "capistrano/#{fetch(:scm)}.rb"
```

Once that is done the recap Capfile template will need to be modified accordingly. The settings in there can be moved to a config/deploy.rb. This means we'll need to update the recap cli installation process.

**Comment by MarkMurphy** [comment]
@manuelmeurer So I guess there's a few places your could look at. You could look though the recap support folder to figure out what we still need in there and/or what needs to be updated. Or you could start rewriting some of the other task files to follow the capistrano 3 format. Or anything I outlined in the above comment. Take your pick.

**Comment by MarkMurphy** [comment]
@tomafro what branch should I base off of? and since this will be a major revision, does that put us at version 3?

**Comment by manuelmeurer** [comment]
Okay, I will have a look around first and try to get a feel for what changed in Cap 3. I think we should definitely bounce Recap to 3.0 as well to indicate that it works for Cap 3.

**Comment by MarkMurphy** [comment]
Yep. You'll find a 3.x branch in my fork of recap (https://github.com/MarkMurphy/recap/tree/3.x).

**Comment by pencilcheck** [comment]
Nope, doesn't work

```
LoadError: cannot load such file -- recap/recipes/rails
```

**Comment by MarkMurphy** [comment]
It's still a work in progress.

**Comment by MarkMurphy** [comment]
@pencilchek you can get it to work by following the setup and authorization guide for capistranno 3. Once your server is setup change your capfile to require recap/setup and recap/deploy

**Comment by MarkMurphy** [comment]
Also note that rollbacks and tasks related to bundler and assets are still incomplete.

**Comment by manuelmeurer** [comment]
@MarkMurphy Sorry I didn't get anything done in the last weeks, work has been overwhelming. I tried to get an overview over how Recap and Capistrano work today, and how capistrano/capistrano#718 fits in, but I have to say I didn't get very far. Since I won't have much time to work on this in the next time, I am sorry to say I can't be of much help right now...

**Comment by MarkMurphy** [comment]
@manuelmeurer No worries. I totally understand.
